name: Android CI

on:
  pull_request:
    types:
      - closed
    branches: [ master ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
        echo "${{ secrets.ANDROID_RELEASE_BASE64_KEY }}" | base64 -d > release.keystore
        export KEYSTORE_PASSWORD="${{ secrets.RELEASE_STORE_PASSWORD }}"
        export KEY_ALIAS="${{ secrets.RELEASE_KEY_ALIAS }}"
        export KEY_PASSWORD="${{ secrets.RELEASE_KEY_PASSWORD }}"
        ./gradlew bundleRelease
    - name: Get aab path
      id: aab-path
      run: |
        path=$(find **/build/outputs/bundle -name '*.aab' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Upload aab file
      uses: actions/upload-artifact@v1
      with:
        name: aab
        path: ${{ steps.aab-path.outputs.path }}
    - name: Distribute App
      run: |
        curl \
        -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
        -F "file=@app/build/outputs/bundle/release/app-release.aab" \
        -F "message=${{github.event.pull_request.title}}/${{github.event.pull_request.body}}" \
        "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
