name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Build Configs
      run:
        chmod +x ./gradlew
    - name: Sign Android release
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: ./app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_RELEASE_BASE64_KEY }}
        alias: ${{ secrets.RELEASE_KEY_ALIAS}}
        keyStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
    - name: Distribute App
      run: |
        curl \
        -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
        -F "file=@app/build/outputs/apk/release/app-release.apk" \
        -F "message=${{github.event.pull_request.title}}" \
        "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
