name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Decode Keystore
      run: |
        echo TEMPDIR = `pwd`
        echo ${{ secrets.ANDROID_RELEASE_BASE64_KEY }} | base64 -d > ./mctodo-keystore.jks
        echo $TEMPDIR
    - name: checkout
      uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Build Configs
      run: |
        echo ${{secrets.ANDROID_RELEASE_BASE64_KEY}} | base64 -d > ./release-application-key
        echo "RELEASE_STORE_FILE=`pwd`/release-application-key" >> ./local.properties
        echo "RELEASE_STORE_PASSWORD=${{secrets.RELEASE_STORE_PASSWORD}}" >> ./local.properties
        echo "RELEASE_KEY_ALIAS={{secrets.RELEASE_KEY_ALIAS}}" >> ./local.properties
        echo "RELEASE_KEY_PASSWORD=${{secrets.RELEASE_KEY_PASSWORD}}" >> ./local.properties
        chmod +x ./gradlew
    - name: Android Release Apk Build
      run: ./gradlew assembleRelease
      env:
        RELEASE_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        RELEASE_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: app/build/outputs/
    - name: Distribute App
      run: |
        curl \
        -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
        -F "file=@app/build/outputs/apk/release/app-release.apk" \
        -F "message=${{github.event.pull_request.title}}" \
        "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
